###
POST http://localhost:3000/register
Content-Type: application/json

{
    "email": "gnani@gmail.com",
    "username": "Gnani",
    "password": "1234"
}

###
POST http://localhost:3000/login
Content-Type: application/json

{
    "email": "gnani@gmail.com",
    "password": "1234"
}